using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ProjektIznynierski.Domain.Abstractions;
using ProjektIznynierski.Domain.Entities;

namespace ProjektIznynierski.Infrastructure.Repositories
{
    public class InvestmentRecommendationPdfService : IInvestmentRecommendationPdfService
    {
        public byte[] GeneratePdf(
            AIAnalysisRequest analysisRequest,
            InvestInstrument instrument,
            FinancialMetric metrics,
            IEnumerable<FinancialReport> reports)
        {
            if (analysisRequest.AIAnalysisResult == null)
                throw new Exception("AIAnalysisResult is missing");

            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30);
                    page.DefaultTextStyle(x => x.FontSize(10));

                    page.Header().Element(e =>
                        BuildHeader(e, analysisRequest, instrument));

                    page.Content().Element(e =>
                        BuildContent(e, analysisRequest, metrics, reports));

                    page.Footer().AlignCenter().Text(text =>
                    {
                        text.Span("Generated by AI Investment Advisory System • ");
                        text.Span(DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm"))
                            .SemiBold();
                    });
                });
            }).GeneratePdf();
        }

        // ================= HEADER =================

        private void BuildHeader(
            IContainer container,
            AIAnalysisRequest request,
            InvestInstrument instrument)
        {
            container.Column(col =>
            {
                col.Item().Text(instrument.Name)
                    .FontSize(18)
                    .Bold();

                col.Item().Text($"Ticker: {instrument.Ticker}");

                col.Item().PaddingVertical(6);

                col.Item().Row(row =>
                {
                    row.RelativeItem()
                        .Text($"Recommendation: {request.AIAnalysisResult!.Recommendation}")
                        .Bold()
                        .FontColor(GetRecommendationColor(
                            request.AIAnalysisResult.Recommendation));

                    row.ConstantItem(160)
                        .AlignRight()
                        .Text($"Confidence: {request.AIAnalysisResult.ConfidenceScore}/100")
                        .SemiBold();
                });

                col.Item().LineHorizontal(1);
            });
        }

        // ================= CONTENT =================

        private void BuildContent(
            IContainer container,
            AIAnalysisRequest request,
            FinancialMetric metrics,
            IEnumerable<FinancialReport> reports)
        {
            container.Column(col =>
            {
                // ===== SUMMARY =====
                col.Item().Text("Summary")
                    .Bold()
                    .FontSize(12);

                col.Item().Text(request.AIAnalysisResult!.Summary);

                col.Item().PaddingVertical(10);

                // ===== KEY INSIGHTS =====
                col.Item().Text("Key Insights")
                    .Bold()
                    .FontSize(12);

                col.Item().Text(request.AIAnalysisResult.KeyInsights);

                col.Item().PaddingVertical(10);

                // ===== FINANCIAL METRICS =====
                col.Item().Text("Financial Metrics")
                    .Bold()
                    .FontSize(12);

                col.Item().Text(
                    $"PE: {metrics.PE ?? 0} | " +
                    $"PB: {metrics.PB ?? 0} | " +
                    $"ROE: {metrics.ROE ?? 0}% | " +
                    $"Debt/Equity: {metrics.DebtToEquity ?? 0} | " +
                    $"Dividend Yield: {metrics.DividendYield ?? 0}%");

                col.Item().PaddingVertical(10);

                // ===== FINANCIAL REPORTS =====
                col.Item().Text("Financial Reports")
                    .Bold()
                    .FontSize(12);

                if (!reports.Any())
                {
                    col.Item().Text("No financial reports available.");
                }
                else
                {
                    foreach (var r in reports)
                    {
                        col.Item()
                            .Background(Colors.Grey.Lighten3)
                            .Padding(6)
                            .Column(rcol =>
                            {
                                rcol.Item()
                                    .Text($"Period: {r.Period}")
                                    .Bold();

                                rcol.Item().Text(
                                    $"Revenue: {r.Revenue} | " +
                                    $"Net Income: {r.NetIncome} | " +
                                    $"EPS: {r.EPS}");

                                rcol.Item().Text(
                                    $"Assets: {r.Assets} | " +
                                    $"Liabilities: {r.Liabilities}");

                                rcol.Item().Text(
                                    $"Operating Cash Flow: {r.OperatingCashFlow} | " +
                                    $"Free Cash Flow: {r.FreeCashFlow}");
                            });

                        col.Item().PaddingBottom(6);
                    }
                }
            });
        }

        // ================= HELPERS =================

        private string GetRecommendationColor(string recommendation)
        {
            return recommendation switch
            {
                "BUY" => Colors.Green.Medium,
                "SELL" => Colors.Red.Medium,
                _ => Colors.Orange.Medium
            };
        }
    }
}
