export const ROUTES = {
  MAIN_MENU: "/mainMenu",
  COMING_SOON: "/ComingSoon",
  LOGIN: "/auth/login",
  LOGIN_EMPLOYEE: "/auth/employee/employeeLoginScreen",
  REGISTER: "/auth/register",
  INVEST_PROFILE: "/investProfile/investProfile",
  WATCHLIST: "/watchList/watchList",
  WALLET: "/wallet/wallet",
  WALLET_HISTORY: "/walletHistory/walletHistory",
  MARKET_DATA: "/marketData",
  INVEST_INSTRUMENT: "/investInstrument/investInstrument",
  FINANCIAL_REPORT: "/financialReport",
  FINANCIAL_METRIC: "/financialMetric/financialMetric",
  FINANCIAL_METRIC_PREVIEW: "/financialMetric/financialMetricPreview",
  FINANCIAL_REPORT_BY_INSTRUMENT:
    "/financialReport/financialReportsByInstrument",
  CREATE_FINANCIAL_REPORT_BY_AI: "/financialReport/createFinancialReportByAI",
  MY_AI_ANALYSIS_REQUESTS: "/aIRequest/myAIRequests",
  AI_ANALYSIS_RESULT: "/aIAnalysisResult/aIAnalysisResult",

  EMPLOYEE_2FA: "/auth/employee/employee2FAScreen",
  EMPLOYEE_MAIN_MENU: "/employeeMainMenu",
  EMPLOYEE_DASHBOARD: "/employee/employeeDashboard",
} as const;
