// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektIznynierski.Infrastructure.Context;

#nullable disable

namespace ProjektIznynierski.Infrastructure.Migrations
{
    [DbContext(typeof(ProjektInzynierskiDbContext))]
    [Migration("20260130173716_RemoveTradeHistory")]
    partial class RemoveTradeHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ProjektInzynierski")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvestProfileRegion", b =>
                {
                    b.Property<int>("InvestProfileId")
                        .HasColumnType("int");

                    b.Property<int>("PreferredRegionsId")
                        .HasColumnType("int");

                    b.HasKey("InvestProfileId", "PreferredRegionsId");

                    b.HasIndex("PreferredRegionsId");

                    b.ToTable("InvestProfileRegions", "ProjektInzynierski");
                });

            modelBuilder.Entity("InvestProfileSector", b =>
                {
                    b.Property<int>("InvestProfileId")
                        .HasColumnType("int");

                    b.Property<int>("PreferredSectorsId")
                        .HasColumnType("int");

                    b.HasKey("InvestProfileId", "PreferredSectorsId");

                    b.HasIndex("PreferredSectorsId");

                    b.ToTable("InvestProfileSectors", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.AIAnalysisRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AIAnalysisResultId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvestInstrumentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AIAnalysisResultId");

                    b.ToTable("AIAnalysisRequests", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.AIAnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyInsights")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("AIAnalysisResults", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvestInstrumentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientID");

                    b.HasIndex("InvestInstrumentID");

                    b.ToTable("Comments", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryRiskLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("Countries", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyRiskLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Currencies", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.CurrencyPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseCurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuoteCurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QuoteCurrencyId");

                    b.HasIndex("BaseCurrencyId", "QuoteCurrencyId")
                        .IsUnique();

                    b.ToTable("CurrencyPairs", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.CurrencyRateHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CloseRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyPairId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HighRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("LowRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("OpenRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyPairId", "Date")
                        .IsUnique();

                    b.ToTable("CurrencyRateHistories", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("TwoFactorCodeExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TwoFactorCodeHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Pesel")
                        .IsUnique();

                    b.ToTable("Employees", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.FinancialMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DebtToEquity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("DividendYield")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("InvestmentInstrumentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PB")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PE")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ROE")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentInstrumentId")
                        .IsUnique();

                    b.ToTable("FinancialMetrics", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.FinancialReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Assets")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EPS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FreeCashFlow")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("InvestInstrumentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Liabilities")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("NetIncome")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("OperatingCashFlow")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvestInstrumentId", "Period")
                        .IsUnique();

                    b.ToTable("FinancialReports", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.InvestHorizon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Horizon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("InvestHorizon", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.InvestInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("FinancialMetricId")
                        .HasColumnType("int");

                    b.Property<int>("InvestmentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("MarketDataDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("Name");

                    b.HasIndex("RegionId");

                    b.HasIndex("SectorId");

                    b.ToTable("InvestInstruments", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.InvestProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcceptableRiskLevelId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InvestHorizonId")
                        .HasColumnType("int");

                    b.Property<double?>("MaxDrawDown")
                        .HasColumnType("float");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<double?>("TargetReturn")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcceptableRiskLevelId");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasFilter("[ClientId] IS NOT NULL");

                    b.HasIndex("InvestHorizonId");

                    b.ToTable("InvestProfiles", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.InvestmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("InvestmentType", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.MarketData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("InvestInstrumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InvestInstrumentId");

                    b.ToTable("MarketData", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("RegionCodeId")
                        .HasColumnType("int");

                    b.Property<int>("RegionRiskLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Regions", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.RegionCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RegionCode", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.RiskLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RiskLevelScale")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RiskLevel", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sectors", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.TradeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TradeTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TradeType", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CashBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasFilter("[ClientId] IS NOT NULL");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Wallets", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.WalletInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvestInstrumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvestInstrumentId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletInstruments", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.WatchList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("WatchLists", "ProjektInzynierski");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.WatchListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvestInstrumentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WatchListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvestInstrumentId");

                    b.HasIndex("WatchListId");

                    b.ToTable("WatchListItems", "ProjektInzynierski");
                });

            modelBuilder.Entity("InvestProfileRegion", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.InvestProfile", null)
                        .WithMany()
                        .HasForeignKey("InvestProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektIznynierski.Domain.Entities.Region", null)
                        .WithMany()
                        .HasForeignKey("PreferredRegionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestProfileSector", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.InvestProfile", null)
                        .WithMany()
                        .HasForeignKey("InvestProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektIznynierski.Domain.Entities.Sector", null)
                        .WithMany()
                        .HasForeignKey("PreferredSectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.AIAnalysisRequest", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.AIAnalysisResult", "AIAnalysisResult")
                        .WithMany()
                        .HasForeignKey("AIAnalysisResultId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AIAnalysisResult");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.AIAnalysisResult", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.Client", "Client")
                        .WithMany("AIAnalysisResults")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Client", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.Country", "Country")
                        .WithMany("Clients")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Comment", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.Client", "Client")
                        .WithMany("Comments")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektIznynierski.Domain.Entities.InvestInstrument", "InvestInstrument")
                        .WithMany("Comments")
                        .HasForeignKey("InvestInstrumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("InvestInstrument");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Country", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektIznynierski.Domain.Entities.Region", "Region")
                        .WithMany("Countries")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.CurrencyPair", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.Currency", "BaseCurrency")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektIznynierski.Domain.Entities.Currency", "QuoteCurrency")
                        .WithMany()
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseCurrency");

                    b.Navigation("QuoteCurrency");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.CurrencyRateHistory", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.CurrencyPair", "CurrencyPair")
                        .WithMany("RateHistory")
                        .HasForeignKey("CurrencyPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrencyPair");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.FinancialMetric", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.InvestInstrument", "InvestmentInstrument")
                        .WithOne("FinancialMetric")
                        .HasForeignKey("ProjektIznynierski.Domain.Entities.FinancialMetric", "InvestmentInstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestmentInstrument");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.FinancialReport", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.InvestInstrument", "InvestInstrument")
                        .WithMany("FinancialReports")
                        .HasForeignKey("InvestInstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvestInstrument");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.InvestInstrument", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektIznynierski.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektIznynierski.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektIznynierski.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Currency");

                    b.Navigation("Region");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.InvestProfile", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.RiskLevel", "AcceptableRiskLevel")
                        .WithMany()
                        .HasForeignKey("AcceptableRiskLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektIznynierski.Domain.Entities.Client", "Client")
                        .WithOne("InvestProfile")
                        .HasForeignKey("ProjektIznynierski.Domain.Entities.InvestProfile", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjektIznynierski.Domain.Entities.InvestHorizon", "InvestHorizon")
                        .WithMany()
                        .HasForeignKey("InvestHorizonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcceptableRiskLevel");

                    b.Navigation("Client");

                    b.Navigation("InvestHorizon");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.MarketData", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.InvestInstrument", "InvestInstrument")
                        .WithMany("MarketData")
                        .HasForeignKey("InvestInstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestInstrument");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.Client", "Client")
                        .WithOne("Wallet")
                        .HasForeignKey("ProjektIznynierski.Domain.Entities.Wallet", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjektIznynierski.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.WalletInstrument", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.InvestInstrument", "InvestInstrument")
                        .WithMany()
                        .HasForeignKey("InvestInstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektIznynierski.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Instruments")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestInstrument");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.WatchList", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.Client", "Client")
                        .WithMany("WatchLists")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.WatchListItem", b =>
                {
                    b.HasOne("ProjektIznynierski.Domain.Entities.InvestInstrument", "InvestInstrument")
                        .WithMany()
                        .HasForeignKey("InvestInstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjektIznynierski.Domain.Entities.WatchList", "WatchList")
                        .WithMany("Items")
                        .HasForeignKey("WatchListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestInstrument");

                    b.Navigation("WatchList");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Client", b =>
                {
                    b.Navigation("AIAnalysisResults");

                    b.Navigation("Comments");

                    b.Navigation("InvestProfile");

                    b.Navigation("Wallet");

                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Country", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.CurrencyPair", b =>
                {
                    b.Navigation("RateHistory");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.InvestInstrument", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FinancialMetric")
                        .IsRequired();

                    b.Navigation("FinancialReports");

                    b.Navigation("MarketData");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Region", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("ProjektIznynierski.Domain.Entities.WatchList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
